# Generated by Django 3.2.18 on 2023-06-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
